### ISSUE TITLE
Improve how to set/override a k8s env var declared within quarkus prop file and using a quarkus prop

### ISSUE THREAD

**Issue by cmoulliard** [halkyonio/primaza-poc#159]
## Improvement

The project includes some properties like this one `servicebox.discovery-application-job.poll-every=5m`
that we could also use as k8s env var: 

`quarkus.kubernetes.env.vars.SERVICEBOX_DISCOVERY_APPLICATION_JOB_POLL_EVERY`

For a kubernetes deployment, we should have the possibility to override the value when we generate the `kubernetes.yml file`. Unfortnately the ENV var is not generated if we declare the property `quarkus.kubernetes.env.vars.SERVICEBOX_DISCOVERY_APPLICATION_JOB_POLL_EVERY=${job.application.poll}` within the application-kubernetes.properties file

Question: What is then the best approach to set such k8s env var for quarkus dekorate ?

**Comment by cmoulliard** [comment]
Georgios tried
```
job.application.poll=3
quarkus.kubernetes.env.vars.SERVICEBOX_DISCOVERY_APPLICATION_JOB_POLL_EVERY=${job.application.poll}
```
which generated
```
   spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: QUARKUS_DATASOURCE_JDBC_URL
              value: jdbc:postgresql://servicebox-app-db:5432/servicebox_database
            - name: QUARKUS_DATASOURCE_USERNAME
              value: user
            - name: QUARKUS_DATASOURCE_PASSWORD
              value: pwd
            - name: SERVICEBOX_DISCOVERY_APPLICATION_JOB_POLL_EVERY
              value: "3"
```
