### ISSUE TITLE
Primaza helm chart cannot be installed

### ISSUE THREAD

**Issue by cmoulliard** [halkyonio/primaza-poc#188]
## Issue

The Primaza helm chart generated using Quarkus dekorate cannot be installed as we got a `cannot unmarshal number into Go struct field EnvVar.spec.template.spec.containers.env.value of type string`
```
[snowdrop@k122-centos7 primaza-poc]$ helm install --devel servicebox-app   --dependency-update   ./servicebox-app/target/helm/kubernetes/servicebox-app   -n primaza   --set app.image=localhost:5000/local/servicebox-app:latest --set app.envs.GIT_SHA_COMMIT=3460572 --set app.envs.QUARKUS_DATASOURCE_USERNAME=user --set app.envs.QUARKUS_DATASOURCE_PASSWORD=pwd --debug
install.go:192: [debug] Original chart version: ""
install.go:194: [debug] setting version to >0.0.0-0
install.go:209: [debug] CHART PATH: /home/snowdrop/primaza-poc/servicebox-app/target/helm/kubernetes/servicebox-app

client.go:128: [debug] creating 9 resource(s)
Error: INSTALLATION FAILED: Deployment in version "v1" cannot be handled as a Deployment: json: cannot unmarshal number into Go struct field EnvVar.spec.template.spec.containers.env.value of type string
```

Ths issue can be fixed if we double quote the following env var `GIT_SHA_COMMIT` with the chart deployment template generated
```
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: QUARKUS_DATASOURCE_JDBC_URL
              value: {{ .Values.app.envs.QUARKUS_DATASOURCE_JDBC_URL }}
            - name: QUARKUS_DATASOURCE_PASSWORD
              value: {{ .Values.app.envs.QUARKUS_DATASOURCE_PASSWORD }}
            - name: GITHUB_REPO
              value: {{ .Values.app.envs.GITHUB_REPO }}
            - name: QUARKUS_DATASOURCE_USERNAME
              value: {{ .Values.app.envs.QUARKUS_DATASOURCE_USERNAME }}
            - name: GIT_SHA_COMMIT
              value: "{{ .Values.app.envs.GIT_SHA_COMMIT }}"
```

Bingo :-) We are getting this error as the SHA commit is `3460572` !! @aureamunoz
