### ISSUE TITLE
TODO to fix workload projection

### ISSUE THREAD

**Issue by cmoulliard** [halkyonio/primaza-poc#193]
## TODO

Tasks to be done:

- [x] Update the f8s syntax to mount only the volume and not volume + envFrom
- [x] Add the needed quarkus dependency
- [x] Find what the `Directory that stores the binding data.` should be - https://redhat-developer.github.io/service-binding-operator/userguide/projecting-binding-data/projecting-binding-data.html
- [x] Populate the secret according to the [WorkloadProjection](https://github.com/servicebinding/spec#example-secret)
- [x] Split from k8s service discovered, the host and the port as they must be passed as separate parameters to the secret
- [x] Add a method able to create properly the secret where:
       - type = DB type name in lowercase (e.g PostgreSQL -> postgresql). 
       - provider = snowdrop
       - url renamed to uri
       - host = hostname of the k8s service
       - port = port of the service
 - [x] We need a new field part of the claim to define the type AND we could reuse the Service type (to be copied to the claim field when service is selected). Remark. We should then create another field to express that Service is part of `something` which corresponds to:  SQL, NoSQL, Broker, .... Api, etc !

**Comment by cmoulliard** [comment]
Questions:

Do we need to create the `database-dir` part of the secret as this example do not include such a directory https://github.com/servicebinding/spec#example-secret ? @iocanel

**Comment by aureamunoz** [comment]
I think Ioannis responded in zulip, quoting:

_The only part where I see it differ is the use of the database, however I am not sure if the spec excludes additional fields.
On the other hand without it its impossilbe to construct the jdbc uri
And the binding framework can't possibly make assumptions on what technology the app is using and thus it's not able to assume jdbc. So, it's 100% needed._

**Comment by cmoulliard** [comment]
Here is how the Deployment should looks like (after SBO updated it) and what we should do using f8 k8s client:
```
k get deployment/spring-petclinic -n my-petclinic -o yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: "2022-12-02T19:03:15Z"
  generation: 2
  labels:
    app: spring-petclinic
  name: spring-petclinic
  namespace: my-petclinic
spec:
  selector:
    matchLabels:
      app: spring-petclinic
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: spring-petclinic
    spec:
      containers:
      - env:
        - name: SPRING_PROFILES_ACTIVE
          value: postgres
        - name: SERVICE_BINDING_ROOT
          value: /bindings
        image: quay.io/service-binding/spring-petclinic:latest
        imagePullPolicy: Always
        name: app
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        resources: {}
        volumeMounts:
        - mountPath: /bindings/spring-petclinic-postgresql
          name: spring-petclinic-postgresql
...
      volumes:
      - name: spring-petclinic-postgresql
        secret:
          defaultMode: 420
          secretName: spring-petclinic-postgresql-73d8585e
```
