### ISSUE TITLE
[Proposition]: Design a bindology service able to map the consumer and service provider parameters

### ISSUE THREAD

**Issue by cmoulliard** [halkyonio/primaza-poc#295]
## Proposition

The [Service Binding Operator](https://github.com/redhat-developer/service-binding-operator) and the Service Binding spec do not really handle a contract definition (= what a consumer application and a service provider will share as list of parameters passed within a secret to configure a datasource, MongoDB, MySQL, ...) as only 2 fields are currently defined as `recommended` part of the [spec](https://github.com/servicebinding/spec#well-known-secret-entries): type and provider.

The consequence is that it is still needed that both (= consumer and provider) verify before to bind a service how the secret should be populated to match exactly what the runtime library expect to get and to consume from the [workload projection](https://github.com/servicebinding/spec#workload-projection) (= where key/values will be stored under the runtime local filesystem mounted from a volume).

To overcome this problem, we propose to design a new service able to perform what it is described hereafter:

- First, it is needed to define, part of a glossary (or bindology), the mappings of some well known services (Postgresql, MySQL, Kafka, A-MQ, Keycloak, ...) and their ServiceBinding Tool's counterpart (see example herefater)
- Next, setup a github flow action, able top of a quarkus release (and quarkiverse extensions) to extract from the existing quarkus code the different properties (datasource, mssql, kafka, mongodb, etc) and to bind them against their corresponding binding parameter (or using a dictionary of synonyms) in a YAML file (optional)
- The YAML file should be hosted under the quarkus github server and be consumable as RAW YAML URL (optional)
- The ServiceBinding tool (running on k8s) can then consume the YAML file of the properties mapped (this file can be pouplated dynamically or manually) to know how to bind/map the parameters they collect (= from a Secret populated by an operator, from a k8s secret if created manually or using SBO, from a different approach) to what the runtime and resource (datasource, etc) expects to have/get

The YAML created/generated file could help to do:

To map them using a glossary to something that the servicebinding tool understands. Example: The datasource expects to get by example the property `jdbc-url` - https://quarkiverse.github.io/quarkiverse-docs/quarkus-jdbc-sqlite/dev/datasource.html. Such a property/parameter is relevant for a java application/runtimes, will be different for nodejs, etc and is not understandable as such by the ServiceBinding tool. If now, we declare somewhere that the property `jdbc-url` for the java runtimes matches the service binding `url`, than the SB tool will be able to populate correctly the following projection
```
apiVersion: v1
kind: Secret
metadata:
  name: production-db-secret
type: servicebinding.io/mysql
stringData:
  type: postgresql   // ServiceBinding spec mandatory param
  provider: bitnami   // ServiceBinding spec mandatory param
  jdbc.url: jdbc:<postgresql>:://<url>:<port>/<database_name> // Java Runtime mandatory param matching service endpoint url
  username: <username_collected_from_vault> // Username to be used to access a service as declared in a vault key secret
  password: <password_collected_from_vault> // Password to be used to access a service as declared in a vault key secret
```

## Where the mapping can take place

We have potentially 2 options, depending where we prefer to do the mapping :
- Application Lib: We improve the spec and extend it to define for different binding types (datasource or db, kafka, mongodb, ...) the parameters they must return part of the secret, response AND then we rely on Application Client Lib to map the binding parameters with their internal parameters (e.g. https://github.com/quarkusio/quarkus/blob/main/extensions/kubernetes-service-binding/runtime/src/main/java/io/quarkus/kubernetes/service/binding/runtime/DatasourceServiceBindingConfigSourceFactory.java#L36). This is what we try todo today without success ! 
- Service Binding / Primaza: We design, part of Primaza, a bindology (word is coming from Ioannis to refer to a glossary of common parameters and their mappings) to let Primaza to return according to the Claim + Runtime type the parameters they expect to get (= sort of contract definition)

WDYT ? @iocanel
